import Head from "next/head";
import Header from "../components/Header";
import AddFinancas from "../components/AddFinancas";
import Cards from "../components/Cards";
import MonthTables from "../components/MonthTables";
import Estatisticas from "../components/Estatisticas";
import Metas from "../components/Metas";
import Footer from "../components/Footer";
import styles from "../styles/HomePage.module.css";

export default function HomePage() {
  return (
    <>
      <Head>
        <title>HomePage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Header />
      </header>

      <main className={styles.main}>
        <AddFinancas />

        <Cards />

        <MonthTables />

        <Estatisticas />

        <Metas />
      </main>

      <footer>
        <Footer />
      </footer>
    </>
  );
}
